name: cuddly-waffle

services:
  front-end:
    build:
      dockerfile: ./docker/front-end.dockerfile
    env_file: .env.local
    ports:
      - 8080:3000

  database:
    build:
      dockerfile: ./docker/postgres-local.dockerfile
    env_file: .env.local
    ports:
      - 5431:5432